server:
  port: 8090

spring:
  application:
    name: Form-Service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: nah
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect