services:
  # PostgreSQL for User Service
    user-db:
      image: postgres:latest
      container_name: user-service-postgres
      environment:
        POSTGRES_DB: userdb
        POSTGRES_USER: ${USER_DB_USERNAME}
        POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
        POSTGRES_HOST_AUTH_METHOD: trust
        POSTGRES_INITDB_ARGS: --auth-host=trust
      ports:
        - "5431:5432"
      volumes:
        - user-data:/var/lib/postgresql/data
      networks:
        - app-network

    # PostgreSQL for Form Service
    form-db:
      image: postgres:latest
      container_name: form-service-postgres
      environment:
        POSTGRES_DB: formdb
        POSTGRES_USER: ${FORM_DB_USERNAME}
        POSTGRES_PASSWORD: ${FORM_DB_PASSWORD}
      ports:
        - "5433:5432"
      volumes:
        - form-data:/var/lib/postgresql/data
      networks:
        - app-network

    # MongoDB for Response Service
    response-db:
      image: mongo:latest
      container_name: response-service-mongodb
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${RESPONSE_DB_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${RESPONSE_DB_PASSWORD}
        MONGO_INITDB_DATABASE: ${RESPONSE_DB_NAME}
      ports:
        - "27017:27017"
      volumes:
        - mongo-data:/data/db
      networks:
        - app-network

networks:
  app-network:
    driver: bridge

volumes:
  user-data:
  form-data:
  mongo-data: