server:
  port: 8080

spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/user/**, /api/v1/auth/oauth2/**, /oauth2/**, /login/**
          filters:
            - AddRequestHeader=X-Gateway-Source, api-gateway
        - id: form-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/forms/**
          filters:
            - AddRequestHeader=X-Gateway-Source, api-gateway

        - id: collaborator-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/forms/*/collaborators/**
          filters:
            - AddRequestHeader=X-Gateway-Source, api-gateway

        - id: question-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/questions/**
          filters:
            - AddRequestHeader=X-Gateway-Source, api-gateway

        - id: option-service
          uri: http://localhost:8090
          predicates:
            - Path=/api/questions/*/options/**
          filters:
            - AddRequestHeader=X-Gateway-Source, api-gateway

        - id: response-service
          uri: http://localhost:8060
          predicates:
            - Path=/api/responses/**
          filters:
            - AddRequestHeader=X-Gateway-Source, api-gateway

        - id: analytics-service
          uri: http://localhost:8060
          predicates:
            - Path=/api/analytics/**
          filters:
            - AddRequestHeader=X-Gateway-Source, api-gateway

jwt:
  secret: ${SECURITY_JWT_SECRET}
  token-expiration: ${SECURITY_JWT_TOKEN_EXPIRATION}

logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO
    reactor.netty: INFO