package org.microservices.userservice.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.microservices.userservice.enums.AuthProvider;
import org.microservices.userservice.enums.Role;

/**
 * Represents a User entity in the application.
 * This entity is mapped to the "users" table in the database.
 * It contains details about the user such as email, password, full name, authentication provider, provider ID, and role.
 */
@Entity
@Table(name = "users")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class User {
    /**
     * The unique identifier for the user.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The email address of the user.
     * Must be unique and cannot be null.
     * Used as the username for authentication.
     */
    @Column(nullable = false, unique = true)
    private String email;

    /**
     * The password of the user.
     * Stored as a hashed value, not in plain text.
     * Cannot be null.
     */
    @Column(nullable = false)
    private String password;

    /**
     * The full name of the user.
     * Cannot be null.
     */
    @Column(nullable = false)
    private String fullName;

    /**
     * The authentication provider used by the user.
     * Can be LOCAL, GOOGLE, GITHUB, etc.
     * Stored as a string representation of the enum.
     */
    @Enumerated(EnumType.STRING)
    @Column(name = "auth_provider")
    private AuthProvider authProvider;

    /**
     * The ID provided by the authentication provider.
     * Used for OAuth2 authentication.
     */
    private String providerId;

    /**
     * The role of the user in the system.
     * Determines the user's permissions.
     * Stored as a string representation of the enum.
     */
    @Enumerated(EnumType.STRING)
    private Role role;

    /**
     * Indicates whether the user account is enabled.
     * Disabled accounts cannot log in.
     * Defaults to false.
     */
    private boolean enabled = false;

}