server:
  port: 8090

spring:
  application:
    name: form-service
  datasource:
    url: ${FORM_DB_URL:jdbc:postgresql://localhost:5433/formdb}
    username: ${FORM_DB_USERNAME:postgres}
    password: ${FORM_DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    compatibility-verifier:
      enabled: false

# User Service configuration
user-service:
  url: ${USER_SERVICE_URL:http://localhost:8070}



logging:
  level:
    org.springframework: INFO
    org.springframework.security: WARN
    org.springframework.web: INFO