name: Docker Build (mp-backend only)

on:
  push:
    branches:
      - backend  
    paths:
      - 'User-Service/**'
      - 'Form-Service/**'
      - 'API-Gateway/**'
      - 'Response-Service/**'
env:
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  

      - name: Detect changed services
        id: changed-services
        uses: tj-actions/changed-files@v44
        with:
          separator: ","
          files: |
            User-Service/**
            Form-Service/**
            API-Gateway/**
            Response-Service/**

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Setup From-Service .env
        if: contains(steps.changed-services.outputs.all_changed_files, 'Form-Service/')
        run: |
          cd Form-Service
          echo "SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}" > .env
          echo "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}" >> .env
          echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" >> .env

      - name: Setup User-Service .env
        if: contains(steps.changed-services.outputs.all_changed_files, 'User-Service/')
        run: |
          cd User-Service
          echo "SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL2 }}" > .env
          echo "SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}" >> .env
          echo "SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}" >> .env
          echo "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID=${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID }}" >> .env
          echo "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET=${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET }}" >> .env
          echo "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID=${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET }}" >> .env
          echo "SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET=${{ secrets.SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET }}" >> .env
          echo "SECURITY_JWT_SECRET=${{ secrets.SECURITY_JWT_SECRET }}" >> .env
          echo "SECURITY_JWT_TOKEN_EXPIRATION=${{ secrets.SECURITY_JWT_TOKEN_EXPIRATION }}" >> .env

      - name: Setup API-Gateway .env
        if: contains(steps.changed-services.outputs.all_changed_files, 'API-Gateway/')
        run: |
          cd API-Gateway
          echo "SECURITY_JWT_SECRET=${{ secrets.SECURITY_JWT_SECRET }}" >> .env
          echo "SECURITY_JWT_TOKEN_EXPIRATION=${{ secrets.SECURITY_JWT_TOKEN_EXPIRATION }}" >> .env

      - name: Build and push User-Service
        if: contains(steps.changed-services.outputs.all_changed_files, 'User-Service/')
        uses: docker/build-push-action@v5
        with:
          context: User-Service
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/user-service:latest

      - name: Build and push Form-Service
        if: contains(steps.changed-services.outputs.all_changed_files, 'Form-Service/')
        uses: docker/build-push-action@v5
        with:
          context: Form-Service
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/form-service:latest
          
      - name: Build and push Response-Service
        if: contains(steps.changed-services.outputs.all_changed_files, 'Response-Service/')
        uses: docker/build-push-action@v5
        with:
          context: Response-Service
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/response-service:latest

      - name: Build and push API-Gateway
        if: contains(steps.changed-services.outputs.all_changed_files, 'API-Gateway/')
        uses: docker/build-push-action@v5
        with:
          context: API-Gateway
          push: true
          tags: ${{ env.DOCKER_USERNAME }}/api-gateway:latest



















